services:
  - type: web
    name: asego-proxy
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TARGET
        value: https://dolphin.asego.in
      - key: ALLOWED_ORIGINS
        value: https://insurance.postmyvisa.com,https://www.insurance.postmyvisa.com,http://localhost:5173,http://localhost:3000
